// Copyright 2014 Mario Guggenberger <mg@protyposis.net>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
using OpenSource.UPnP;
using System;

namespace LocalAudioBroadcast
{
    /// <summary>
    /// Transparent DeviceSide UPnP Service
    /// </summary>
    public class DvContentDirectory : IUPnPService
    {

        // Place your declarations above this line

        #region AutoGenerated Code Section [Do NOT Modify, unless you know what you're doing]
        //{{{{{ Begin Code Block

        private _DvContentDirectory _S;
        public static string URN = "urn:schemas-upnp-org:service:ContentDirectory:1";
        public double VERSION
        {
           get
           {
               return(double.Parse(_S.GetUPnPService().Version));
           }
        }

        public enum Enum_A_ARG_TYPE_BrowseFlag
        {
            BROWSEMETADATA,
            BROWSEDIRECTCHILDREN,
        }
        public Enum_A_ARG_TYPE_BrowseFlag A_ARG_TYPE_BrowseFlag
        {
            set
            {
               string v = "";
               switch(value)
               {
                  case Enum_A_ARG_TYPE_BrowseFlag.BROWSEMETADATA:
                     v = "BrowseMetadata";
                     break;
                  case Enum_A_ARG_TYPE_BrowseFlag.BROWSEDIRECTCHILDREN:
                     v = "BrowseDirectChildren";
                     break;
               }
               _S.SetStateVariable("A_ARG_TYPE_BrowseFlag",v);
            }
            get
            {
               Enum_A_ARG_TYPE_BrowseFlag RetVal = 0;
               string v = (string)_S.GetStateVariable("A_ARG_TYPE_BrowseFlag");
               switch(v)
               {
                  case "BrowseMetadata":
                     RetVal = Enum_A_ARG_TYPE_BrowseFlag.BROWSEMETADATA;
                     break;
                  case "BrowseDirectChildren":
                     RetVal = Enum_A_ARG_TYPE_BrowseFlag.BROWSEDIRECTCHILDREN;
                     break;
               }
               return(RetVal);
           }
        }
        static public string Enum_A_ARG_TYPE_BrowseFlag_ToString(Enum_A_ARG_TYPE_BrowseFlag en)
        {
            string RetVal = "";
            switch(en)
            {
                case Enum_A_ARG_TYPE_BrowseFlag.BROWSEMETADATA:
                    RetVal = "BrowseMetadata";
                    break;
                case Enum_A_ARG_TYPE_BrowseFlag.BROWSEDIRECTCHILDREN:
                    RetVal = "BrowseDirectChildren";
                    break;
            }
            return(RetVal);
        }
        static public string[] Values_A_ARG_TYPE_BrowseFlag
        {
            get
            {
                string[] RetVal = new string[2]{"BrowseDirectChildren","BrowseMetadata"};
                return(RetVal);
            }
        }
        public delegate void OnStateVariableModifiedHandler(DvContentDirectory sender);
        public event OnStateVariableModifiedHandler OnStateVariableModified_SortCapabilities;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_SearchCriteria;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_SortCriteria;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_Result;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_BrowseFlag;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_UpdateID;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_Filter;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_Index;
        public event OnStateVariableModifiedHandler OnStateVariableModified_SearchCapabilities;
        public event OnStateVariableModifiedHandler OnStateVariableModified_ContainerUpdateIDs;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_ObjectID;
        public event OnStateVariableModifiedHandler OnStateVariableModified_SystemUpdateID;
        public event OnStateVariableModifiedHandler OnStateVariableModified_A_ARG_TYPE_Count;
        public System.String SortCapabilities
        {
            get
            {
               return((System.String)_S.GetStateVariable("SortCapabilities"));
            }
            set
            {
               _S.SetStateVariable("SortCapabilities", value);
            }
        }
        public System.String A_ARG_TYPE_SearchCriteria
        {
            get
            {
               return((System.String)_S.GetStateVariable("A_ARG_TYPE_SearchCriteria"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_SearchCriteria", value);
            }
        }
        public System.String A_ARG_TYPE_SortCriteria
        {
            get
            {
               return((System.String)_S.GetStateVariable("A_ARG_TYPE_SortCriteria"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_SortCriteria", value);
            }
        }
        public System.String A_ARG_TYPE_Result
        {
            get
            {
               return((System.String)_S.GetStateVariable("A_ARG_TYPE_Result"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_Result", value);
            }
        }
        public System.UInt32 A_ARG_TYPE_UpdateID
        {
            get
            {
               return((System.UInt32)_S.GetStateVariable("A_ARG_TYPE_UpdateID"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_UpdateID", value);
            }
        }
        public System.String A_ARG_TYPE_Filter
        {
            get
            {
               return((System.String)_S.GetStateVariable("A_ARG_TYPE_Filter"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_Filter", value);
            }
        }
        public System.UInt32 A_ARG_TYPE_Index
        {
            get
            {
               return((System.UInt32)_S.GetStateVariable("A_ARG_TYPE_Index"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_Index", value);
            }
        }
        public System.String SearchCapabilities
        {
            get
            {
               return((System.String)_S.GetStateVariable("SearchCapabilities"));
            }
            set
            {
               _S.SetStateVariable("SearchCapabilities", value);
            }
        }
        public System.String Evented_ContainerUpdateIDs
        {
            get
            {
               return((System.String)_S.GetStateVariable("ContainerUpdateIDs"));
            }
            set
            {
               _S.SetStateVariable("ContainerUpdateIDs", value);
            }
        }
        public System.String A_ARG_TYPE_ObjectID
        {
            get
            {
               return((System.String)_S.GetStateVariable("A_ARG_TYPE_ObjectID"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_ObjectID", value);
            }
        }
        public System.UInt32 Evented_SystemUpdateID
        {
            get
            {
               return((System.UInt32)_S.GetStateVariable("SystemUpdateID"));
            }
            set
            {
               _S.SetStateVariable("SystemUpdateID", value);
            }
        }
        public System.UInt32 A_ARG_TYPE_Count
        {
            get
            {
               return((System.UInt32)_S.GetStateVariable("A_ARG_TYPE_Count"));
            }
            set
            {
               _S.SetStateVariable("A_ARG_TYPE_Count", value);
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_SortCapabilities
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SortCapabilities")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SortCapabilities")).Accumulator = value;
            }
        }
        public double ModerationDuration_SortCapabilities
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SortCapabilities")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SortCapabilities")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_SearchCriteria
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_SearchCriteria
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_SortCriteria
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_SortCriteria
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_Result
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_Result
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_BrowseFlag
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_BrowseFlag
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_UpdateID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_UpdateID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_Filter
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_Filter
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_Index
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_Index
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_SearchCapabilities
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SearchCapabilities")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SearchCapabilities")).Accumulator = value;
            }
        }
        public double ModerationDuration_SearchCapabilities
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SearchCapabilities")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SearchCapabilities")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_ContainerUpdateIDs
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs")).Accumulator = value;
            }
        }
        public double ModerationDuration_ContainerUpdateIDs
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_ObjectID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_ObjectID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_SystemUpdateID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SystemUpdateID")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SystemUpdateID")).Accumulator = value;
            }
        }
        public double ModerationDuration_SystemUpdateID
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SystemUpdateID")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("SystemUpdateID")).ModerationPeriod = value;
            }
        }
        public UPnPModeratedStateVariable.IAccumulator Accumulator_A_ARG_TYPE_Count
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count")).Accumulator);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count")).Accumulator = value;
            }
        }
        public double ModerationDuration_A_ARG_TYPE_Count
        {
            get
            {
                 return(((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count")).ModerationPeriod);
            }
            set
            {
                 ((UPnPModeratedStateVariable)_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count")).ModerationPeriod = value;
            }
        }
        public delegate void Delegate_Browse(System.String ObjectID, DvContentDirectory.Enum_A_ARG_TYPE_BrowseFlag BrowseFlag, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID);
        public delegate void Delegate_GetSearchCapabilities(out System.String SearchCaps);
        public delegate void Delegate_GetSortCapabilities(out System.String SortCaps);
        public delegate void Delegate_GetSystemUpdateID(out System.UInt32 Id);
        public delegate void Delegate_Search(System.String ContainerID, System.String SearchCriteria, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID);

        public Delegate_Browse External_Browse = null;
        public Delegate_GetSearchCapabilities External_GetSearchCapabilities = null;
        public Delegate_GetSortCapabilities External_GetSortCapabilities = null;
        public Delegate_GetSystemUpdateID External_GetSystemUpdateID = null;
        public Delegate_Search External_Search = null;

        public void RemoveStateVariable_SortCapabilities()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("SortCapabilities"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_SearchCriteria()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_SortCriteria()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_Result()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_BrowseFlag()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_UpdateID()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_Filter()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_Index()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index"));
        }
        public void RemoveStateVariable_SearchCapabilities()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("SearchCapabilities"));
        }
        public void RemoveStateVariable_ContainerUpdateIDs()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_ObjectID()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID"));
        }
        public void RemoveStateVariable_SystemUpdateID()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("SystemUpdateID"));
        }
        public void RemoveStateVariable_A_ARG_TYPE_Count()
        {
            _S.GetUPnPService().RemoveStateVariable(_S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count"));
        }
        public void RemoveAction_Browse()
        {
             _S.GetUPnPService().RemoveMethod("Browse");
        }
        public void RemoveAction_GetSearchCapabilities()
        {
             _S.GetUPnPService().RemoveMethod("GetSearchCapabilities");
        }
        public void RemoveAction_GetSortCapabilities()
        {
             _S.GetUPnPService().RemoveMethod("GetSortCapabilities");
        }
        public void RemoveAction_GetSystemUpdateID()
        {
             _S.GetUPnPService().RemoveMethod("GetSystemUpdateID");
        }
        public void RemoveAction_Search()
        {
             _S.GetUPnPService().RemoveMethod("Search");
        }
        public System.Net.IPEndPoint GetCaller()
        {
             return(_S.GetUPnPService().GetCaller());
        }
        public System.Net.IPEndPoint GetReceiver()
        {
             return(_S.GetUPnPService().GetReceiver());
        }

        private class _DvContentDirectory
        {
            private DvContentDirectory Outer = null;
            private UPnPService S;
            internal _DvContentDirectory(DvContentDirectory n)
            {
                Outer = n;
                S = BuildUPnPService();
            }
            public UPnPService GetUPnPService()
            {
                return(S);
            }
            public void SetStateVariable(string VarName, object VarValue)
            {
               S.SetStateVariable(VarName,VarValue);
            }
            public object GetStateVariable(string VarName)
            {
               return(S.GetStateVariable(VarName));
            }
            protected UPnPService BuildUPnPService()
            {
                UPnPStateVariable[] RetVal = new UPnPStateVariable[13];
                RetVal[0] = new UPnPModeratedStateVariable("SortCapabilities", typeof(System.String), false);
                RetVal[0].AddAssociation("GetSortCapabilities", "SortCaps");
                RetVal[1] = new UPnPModeratedStateVariable("A_ARG_TYPE_SearchCriteria", typeof(System.String), false);
                RetVal[1].AddAssociation("Search", "SearchCriteria");
                RetVal[2] = new UPnPModeratedStateVariable("A_ARG_TYPE_SortCriteria", typeof(System.String), false);
                RetVal[2].AddAssociation("Browse", "SortCriteria");
                RetVal[2].AddAssociation("Search", "SortCriteria");
                RetVal[3] = new UPnPModeratedStateVariable("A_ARG_TYPE_Result", typeof(System.String), false);
                RetVal[3].AddAssociation("Browse", "Result");
                RetVal[3].AddAssociation("Search", "Result");
                RetVal[4] = new UPnPModeratedStateVariable("A_ARG_TYPE_BrowseFlag", typeof(System.String), false);
                RetVal[4].AllowedStringValues = new string[2]{"BrowseMetadata", "BrowseDirectChildren"};
                RetVal[4].AddAssociation("Browse", "BrowseFlag");
                RetVal[5] = new UPnPModeratedStateVariable("A_ARG_TYPE_UpdateID", typeof(System.UInt32), false);
                RetVal[5].AddAssociation("Browse", "UpdateID");
                RetVal[5].AddAssociation("Search", "UpdateID");
                RetVal[6] = new UPnPModeratedStateVariable("A_ARG_TYPE_Filter", typeof(System.String), false);
                RetVal[6].AddAssociation("Browse", "Filter");
                RetVal[6].AddAssociation("Search", "Filter");
                RetVal[7] = new UPnPModeratedStateVariable("A_ARG_TYPE_Index", typeof(System.UInt32), false);
                RetVal[7].AddAssociation("Browse", "StartingIndex");
                RetVal[7].AddAssociation("Search", "StartingIndex");
                RetVal[8] = new UPnPModeratedStateVariable("SearchCapabilities", typeof(System.String), false);
                RetVal[8].AddAssociation("GetSearchCapabilities", "SearchCaps");
                RetVal[9] = new UPnPModeratedStateVariable("ContainerUpdateIDs", typeof(System.String), true);
                RetVal[10] = new UPnPModeratedStateVariable("A_ARG_TYPE_ObjectID", typeof(System.String), false);
                RetVal[10].AddAssociation("Browse", "ObjectID");
                RetVal[10].AddAssociation("Search", "ContainerID");
                RetVal[11] = new UPnPModeratedStateVariable("SystemUpdateID", typeof(System.UInt32), true);
                RetVal[11].AddAssociation("GetSystemUpdateID", "Id");
                RetVal[12] = new UPnPModeratedStateVariable("A_ARG_TYPE_Count", typeof(System.UInt32), false);
                RetVal[12].AddAssociation("Browse", "RequestedCount");
                RetVal[12].AddAssociation("Browse", "NumberReturned");
                RetVal[12].AddAssociation("Browse", "TotalMatches");
                RetVal[12].AddAssociation("Search", "RequestedCount");
                RetVal[12].AddAssociation("Search", "NumberReturned");
                RetVal[12].AddAssociation("Search", "TotalMatches");

                UPnPService S = new UPnPService(1, "urn:upnp-org:serviceId:ContentDirectory", URN, true, this);
                for(int i=0;i<RetVal.Length;++i)
                {
                   S.AddStateVariable(RetVal[i]);
                }
                S.AddMethod("Browse");
                S.AddMethod("GetSearchCapabilities");
                S.AddMethod("GetSortCapabilities");
                S.AddMethod("GetSystemUpdateID");
                S.AddMethod("Search");
                return(S);
            }

            public void Browse(System.String ObjectID, System.String BrowseFlag, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID)
            {
                Enum_A_ARG_TYPE_BrowseFlag e_BrowseFlag;
                switch(BrowseFlag)
                {
                    case "BrowseMetadata":
                        e_BrowseFlag = Enum_A_ARG_TYPE_BrowseFlag.BROWSEMETADATA;
                        break;
                    case "BrowseDirectChildren":
                        e_BrowseFlag = Enum_A_ARG_TYPE_BrowseFlag.BROWSEDIRECTCHILDREN;
                        break;
                    default:
                        e_BrowseFlag = 0;
                        break;
                }
                if (Outer.External_Browse != null)
                {
                    Outer.External_Browse(ObjectID, e_BrowseFlag, Filter, StartingIndex, RequestedCount, SortCriteria, out Result, out NumberReturned, out TotalMatches, out UpdateID);
                }
                else
                {
                    Sink_Browse(ObjectID, e_BrowseFlag, Filter, StartingIndex, RequestedCount, SortCriteria, out Result, out NumberReturned, out TotalMatches, out UpdateID);
                }
            }
            public void GetSearchCapabilities(out System.String SearchCaps)
            {
                if (Outer.External_GetSearchCapabilities != null)
                {
                    Outer.External_GetSearchCapabilities(out SearchCaps);
                }
                else
                {
                    Sink_GetSearchCapabilities(out SearchCaps);
                }
            }
            public void GetSortCapabilities(out System.String SortCaps)
            {
                if (Outer.External_GetSortCapabilities != null)
                {
                    Outer.External_GetSortCapabilities(out SortCaps);
                }
                else
                {
                    Sink_GetSortCapabilities(out SortCaps);
                }
            }
            public void GetSystemUpdateID(out System.UInt32 Id)
            {
                if (Outer.External_GetSystemUpdateID != null)
                {
                    Outer.External_GetSystemUpdateID(out Id);
                }
                else
                {
                    Sink_GetSystemUpdateID(out Id);
                }
            }
            public void Search(System.String ContainerID, System.String SearchCriteria, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID)
            {
                if (Outer.External_Search != null)
                {
                    Outer.External_Search(ContainerID, SearchCriteria, Filter, StartingIndex, RequestedCount, SortCriteria, out Result, out NumberReturned, out TotalMatches, out UpdateID);
                }
                else
                {
                    Sink_Search(ContainerID, SearchCriteria, Filter, StartingIndex, RequestedCount, SortCriteria, out Result, out NumberReturned, out TotalMatches, out UpdateID);
                }
            }

            public Delegate_Browse Sink_Browse;
            public Delegate_GetSearchCapabilities Sink_GetSearchCapabilities;
            public Delegate_GetSortCapabilities Sink_GetSortCapabilities;
            public Delegate_GetSystemUpdateID Sink_GetSystemUpdateID;
            public Delegate_Search Sink_Search;
        }
        public DvContentDirectory()
        {
            _S = new _DvContentDirectory(this);
            _S.GetUPnPService().GetStateVariableObject("SortCapabilities").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_SortCapabilities);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SearchCriteria").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_SearchCriteria);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_SortCriteria").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_SortCriteria);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Result").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_Result);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_BrowseFlag").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_BrowseFlag);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_UpdateID").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_UpdateID);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Filter").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_Filter);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Index").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_Index);
            _S.GetUPnPService().GetStateVariableObject("SearchCapabilities").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_SearchCapabilities);
            _S.GetUPnPService().GetStateVariableObject("ContainerUpdateIDs").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_ContainerUpdateIDs);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_ObjectID").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_ObjectID);
            _S.GetUPnPService().GetStateVariableObject("SystemUpdateID").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_SystemUpdateID);
            _S.GetUPnPService().GetStateVariableObject("A_ARG_TYPE_Count").OnModified += new UPnPStateVariable.ModifiedHandler(OnModifiedSink_A_ARG_TYPE_Count);
            _S.Sink_Browse = new Delegate_Browse(Browse);
            _S.Sink_GetSearchCapabilities = new Delegate_GetSearchCapabilities(GetSearchCapabilities);
            _S.Sink_GetSortCapabilities = new Delegate_GetSortCapabilities(GetSortCapabilities);
            _S.Sink_GetSystemUpdateID = new Delegate_GetSystemUpdateID(GetSystemUpdateID);
            _S.Sink_Search = new Delegate_Search(Search);
        }
        public DvContentDirectory(string ID):this()
        {
            _S.GetUPnPService().ServiceID = ID;
        }
        public UPnPService GetUPnPService()
        {
            return(_S.GetUPnPService());
        }
        private void OnModifiedSink_SortCapabilities(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_SortCapabilities != null) OnStateVariableModified_SortCapabilities(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_SearchCriteria(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_SearchCriteria != null) OnStateVariableModified_A_ARG_TYPE_SearchCriteria(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_SortCriteria(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_SortCriteria != null) OnStateVariableModified_A_ARG_TYPE_SortCriteria(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_Result(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_Result != null) OnStateVariableModified_A_ARG_TYPE_Result(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_BrowseFlag(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_BrowseFlag != null) OnStateVariableModified_A_ARG_TYPE_BrowseFlag(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_UpdateID(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_UpdateID != null) OnStateVariableModified_A_ARG_TYPE_UpdateID(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_Filter(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_Filter != null) OnStateVariableModified_A_ARG_TYPE_Filter(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_Index(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_Index != null) OnStateVariableModified_A_ARG_TYPE_Index(this);
        }
        private void OnModifiedSink_SearchCapabilities(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_SearchCapabilities != null) OnStateVariableModified_SearchCapabilities(this);
        }
        private void OnModifiedSink_ContainerUpdateIDs(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_ContainerUpdateIDs != null) OnStateVariableModified_ContainerUpdateIDs(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_ObjectID(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_ObjectID != null) OnStateVariableModified_A_ARG_TYPE_ObjectID(this);
        }
        private void OnModifiedSink_SystemUpdateID(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_SystemUpdateID != null) OnStateVariableModified_SystemUpdateID(this);
        }
        private void OnModifiedSink_A_ARG_TYPE_Count(UPnPStateVariable sender, object NewValue)
        {
            if (OnStateVariableModified_A_ARG_TYPE_Count != null) OnStateVariableModified_A_ARG_TYPE_Count(this);
        }
        //}}}}} End of Code Block

        #endregion

        /// <summary>
        /// Action: Browse
        /// </summary>
        /// <param name="ObjectID">Associated State Variable: A_ARG_TYPE_ObjectID</param>
        /// <param name="BrowseFlag">Associated State Variable: A_ARG_TYPE_BrowseFlag</param>
        /// <param name="Filter">Associated State Variable: A_ARG_TYPE_Filter</param>
        /// <param name="StartingIndex">Associated State Variable: A_ARG_TYPE_Index</param>
        /// <param name="RequestedCount">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="SortCriteria">Associated State Variable: A_ARG_TYPE_SortCriteria</param>
        /// <param name="Result">Associated State Variable: A_ARG_TYPE_Result</param>
        /// <param name="NumberReturned">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="TotalMatches">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="UpdateID">Associated State Variable: A_ARG_TYPE_UpdateID</param>
        public void Browse(System.String ObjectID, Enum_A_ARG_TYPE_BrowseFlag BrowseFlag, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID)
        {
            Console.WriteLine("DIRECTORY ContentDirectory_Browse(" + ObjectID.ToString() + BrowseFlag.ToString() + Filter.ToString() + StartingIndex.ToString() + RequestedCount.ToString() + SortCriteria.ToString() + ")");
            //ToDo: Add Your implementation here, and remove exception
            throw (new UPnPCustomException(800, "This method has not been completely implemented..."));
        }
        /// <summary>
        /// Action: GetSearchCapabilities
        /// </summary>
        /// <param name="SearchCaps">Associated State Variable: SearchCapabilities</param>
        public void GetSearchCapabilities(out System.String SearchCaps)
        {
            //ToDo: Add Your implementation here, and remove exception
            throw(new UPnPCustomException(800,"This method has not been completely implemented..."));
        }
        /// <summary>
        /// Action: GetSortCapabilities
        /// </summary>
        /// <param name="SortCaps">Associated State Variable: SortCapabilities</param>
        public void GetSortCapabilities(out System.String SortCaps)
        {
            //ToDo: Add Your implementation here, and remove exception
            throw(new UPnPCustomException(800,"This method has not been completely implemented..."));
        }
        /// <summary>
        /// Action: GetSystemUpdateID
        /// </summary>
        /// <param name="Id">Associated State Variable: SystemUpdateID</param>
        public void GetSystemUpdateID(out System.UInt32 Id)
        {
            //ToDo: Add Your implementation here, and remove exception
            throw(new UPnPCustomException(800,"This method has not been completely implemented..."));
        }
        /// <summary>
        /// Action: Search
        /// </summary>
        /// <param name="ContainerID">Associated State Variable: A_ARG_TYPE_ObjectID</param>
        /// <param name="SearchCriteria">Associated State Variable: A_ARG_TYPE_SearchCriteria</param>
        /// <param name="Filter">Associated State Variable: A_ARG_TYPE_Filter</param>
        /// <param name="StartingIndex">Associated State Variable: A_ARG_TYPE_Index</param>
        /// <param name="RequestedCount">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="SortCriteria">Associated State Variable: A_ARG_TYPE_SortCriteria</param>
        /// <param name="Result">Associated State Variable: A_ARG_TYPE_Result</param>
        /// <param name="NumberReturned">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="TotalMatches">Associated State Variable: A_ARG_TYPE_Count</param>
        /// <param name="UpdateID">Associated State Variable: A_ARG_TYPE_UpdateID</param>
        public void Search(System.String ContainerID, System.String SearchCriteria, System.String Filter, System.UInt32 StartingIndex, System.UInt32 RequestedCount, System.String SortCriteria, out System.String Result, out System.UInt32 NumberReturned, out System.UInt32 TotalMatches, out System.UInt32 UpdateID)
        {
            //ToDo: Add Your implementation here, and remove exception
            throw(new UPnPCustomException(800,"This method has not been completely implemented..."));
        }
    }
}